In [ ]:
# To-DO -Task

#4.1- Array Creation

import numpy as np

#1.1
array_1 =np.zeros((2,2))
array_1

array([[0., 0.],
       [0., 0.]])

In [ ]:

#1.2
array_2 = np.ones((4,2))
array_2

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
#1.3
array_3 =np.full((4,2), fill_value=111)
print("array with given shape and type:")
array_3

array with given shape and type:


array([[111, 111],
       [111, 111],
       [111, 111],
       [111, 111]])

In [ ]:
#1.4
array_4 =np.zeros_like((array_3))
print(array_4)

[[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
#1.5
array_5 =np.ones_like((array_4))
array_5

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
#1.6
a=[1,2,3,4]
array_6=np.array(a)
array_6

array([1, 2, 3, 4])

In [ ]:
#4.1.1 problem 2
#2.1
array_1 = np.arange(10, 49)
array_1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
#2.2
array_2= np.arange(9).reshape(3,3)
array_2


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#2.3
array_3=np.eye(3)
array_3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#2.4
array_4=np.random.random(30)
array_4
array_4 =np.mean(array_4)
array_4


0.4583967750209341

In [ ]:
#2.5
array_5 =np.random.rand(10,10), np.max, np.min
array_5


(array([[0.76210698, 0.04740241, 0.05496372, 0.07695067, 0.32211557,
         0.18481094, 0.92303087, 0.35789451, 0.68823514, 0.9226721 ],
        [0.75310947, 0.96893764, 0.89664732, 0.38482241, 0.93994573,
         0.83346018, 0.09895475, 0.24335712, 0.15269393, 0.55300678],
        [0.93681446, 0.05683862, 0.57711174, 0.94838408, 0.25552451,
         0.53722547, 0.8630623 , 0.35956589, 0.17476938, 0.50428212],
        [0.73638724, 0.8142034 , 0.42540364, 0.18247647, 0.86892034,
         0.64007391, 0.59080703, 0.67169479, 0.49940359, 0.04408197],
        [0.49144325, 0.59040253, 0.6334527 , 0.26530038, 0.87019348,
         0.15392074, 0.72198974, 0.87434944, 0.157402  , 0.541256  ],
        [0.31236144, 0.54134956, 0.62334523, 0.52799866, 0.44147092,
         0.41593189, 0.74359759, 0.47207684, 0.510091  , 0.77411989],
        [0.53981795, 0.37798436, 0.63772321, 0.06940485, 0.64280432,
         0.95475135, 0.15971298, 0.23394663, 0.09115151, 0.20955236],
        [0.2178624 , 0.1042

In [ ]:
#2.6
array_6 =np.zeros(10)
array_6

array_6[4]=1
array_6

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
#2.7
arr =[1,2,0,0,4,0]
array_7= np.flip(arr)
array_7

array([0, 4, 0, 0, 2, 1])

In [ ]:
#2.8
array_8 = np.ones((5, 5))
print("1 on the border and 0 inside in the array:")
array_8[1:-1, 1:-1] = 0
(array_8)


1 on the border and 0 inside in the array:


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#2.9
array_9 = np.zeros((8,7))

array_9 [1::2, ::2] =1
array_9[::2, 1::2] =1
array_9

array([[0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1.]])

In [ ]:
#problem-3
#3.1
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

arr=np.add(x,y)
arr

array([[ 6,  8],
       [10, 13]])

In [ ]:
#3.2
arr_2=np.subtract(x,y)
arr_2

array([[-4, -4],
       [-4, -3]])

In [ ]:
#3.3
arr_3= np.multiply(3, x)
arr_3

array([[ 3,  6],
       [ 9, 15]])

In [ ]:
#3.4
square1= np.square(x)
square1
square2=np.square(y)
square2

array([[25, 36],
       [49, 64]])

In [ ]:
#3.5
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
dot1 = np.dot(x,y)
print(dot1)

v = np.array([9,10])
w = np.array([11,12])
dot2 = np.dot(v,w)
print(dot2)

dot3 = np.dot(x,v)
print(dot3)

[[19 22]
 [50 58]]
219
[29 77]


In [ ]:
#3.6
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])
concate1 = np.concatenate((x,y), axis=1)
print(concate1)

concate2= np.concatenate((v,w), axis =0)
print(concate2)

[[1 2 5 6]
 [3 5 7 8]]
[ 9 10 11 12]


In [ ]:
#3.7
concate3 = np.concatenate((x,v))
# We get error because all the inputes arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s).

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
#Problem-4

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [3]:
#4.1
#Prove A.A−1 = I
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("1. A * A^(-1) = I:")
print(identity_check)

1. A * A^(-1) = I:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [5]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n. AB != BA:")
print("AB:")
print(AB)
print("BA:")
print(BA)
print("Are AB and BA equal? ", np.array_equal(AB, BA))


. AB != BA:
AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
Are AB and BA equal?  False


In [6]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
AB_transpose = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("\n3. (AB)^T = B^T * A^T:")
print("(AB)^T:")
print(AB_transpose)
print("B^T * A^T:")
print(BT_AT)
print("Are (AB)^T and B^T * A^T equal? ", np.array_equal(AB_transpose, BT_AT))



3. (AB)^T = B^T * A^T:
(AB)^T:
[[23 51]
 [13 29]]
B^T * A^T:
[[23 51]
 [13 29]]
Are (AB)^T and B^T * A^T equal?  True


In [ ]:

import numpy as np
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

print("inverse:\n", np.linalg.inv(A))

X = np.dot(A_inv, B)
print("Solution x:", np.linalg.solve(A, B))



inverse:
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]
Solution x: [ 2.  1. -2.]
